version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: teacher-student-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: teacher-student-app
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_dev_data:

networks:
  app-network:
    driver: bridge
