version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: teacher-student-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: teacher-student-app
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network

  app:
    build: .
    container_name: teacher-student-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/teacher-student-app?authSource=admin
      JWT_SECRET: your_jwt_secret_key_here_change_in_production
      NODE_ENV: production
    depends_on:
      - mongodb
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
